CONTIKI_PROJECT = example-shell
all: $(CONTIKI_PROJECT)

APPS = serial-shell
CONTIKI = ../..
DEFINES=
#CFLAGS+=-Werror
COFFEE_FILES=4
#PROJECT_SOURCEFILES+=apps/codeprop/tcp_loader2.c
#COFFEE_ADDRESS=0x1f000
#DEFINES=COFFEE_FILES=3

include $(CONTIKI)/Makefile.include
